name: Portfolio CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
        types: [assigned]
  issue_comment:
        types: [created]
jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      #installs Node Module to run the code
    - name: Install dependencies
      run: npm install
      #Builds the angular application using node and in production mode
    - name: Build
      run: npm run build  --prod 
